import type { EventTemplate } from '@/types'
import type { Language } from '@/types'

type TemplateStrings = { name: string; description: string; summary: string; eventDescription?: string }

const TEMPLATE_I18N: Record<string, Record<Language, TemplateStrings>> = {
  'builtin-meeting': {
    en: { name: 'Team Meeting', description: 'Standard team meeting with video call', summary: 'Team Meeting', eventDescription: 'Weekly team sync-up' },
    es: { name: 'Reunión de equipo', description: 'Reunión estándar con videollamada', summary: 'Reunión de equipo', eventDescription: 'Sincronización semanal del equipo' },
    ro: { name: 'Ședință de echipă', description: 'Ședință standard cu apel video', summary: 'Ședință de echipă', eventDescription: 'Sincronizare săptămânală a echipei' },
  },
  'builtin-birthday': {
    en: { name: 'Birthday', description: 'All-day birthday celebration', summary: 'Birthday', eventDescription: 'Happy Birthday! 🎉' },
    es: { name: 'Cumpleaños', description: 'Celebración de cumpleaños todo el día', summary: 'Cumpleaños', eventDescription: '¡Feliz cumpleaños! 🎉' },
    ro: { name: 'Zi de naștere', description: 'Celebrare de ziua de naștere toată ziua', summary: 'Zi de naștere', eventDescription: 'La mulți ani! 🎉' },
  },
  'builtin-doctor': {
    en: { name: 'Doctor Appointment', description: 'Medical appointment with reminder', summary: 'Doctor Appointment' },
    es: { name: 'Cita médica', description: 'Consulta médica con recordatorio', summary: 'Cita médica' },
    ro: { name: 'Consultație medicală', description: 'Programare la medic cu memento', summary: 'Consultație medicală' },
  },
  'builtin-workout': {
    en: { name: 'Workout', description: 'Exercise session', summary: 'Workout' },
    es: { name: 'Entrenamiento', description: 'Sesión de ejercicio', summary: 'Entrenamiento' },
    ro: { name: 'Antrenament', description: 'Sesiune de exerciții', summary: 'Antrenament' },
  },
  'builtin-dinner': {
    en: { name: 'Dinner Reservation', description: 'Restaurant dinner with location', summary: 'Dinner Reservation' },
    es: { name: 'Reserva de cena', description: 'Cena en restaurante con ubicación', summary: 'Reserva de cena' },
    ro: { name: 'Rezervare cină', description: 'Cină la restaurant cu locație', summary: 'Rezervare cină' },
  },
  'builtin-flight': {
    en: { name: 'Flight', description: 'Air travel with early reminder', summary: 'Flight', eventDescription: 'Flight details:\nAirline: \nFlight #: \nGate: ' },
    es: { name: 'Vuelo', description: 'Viaje aéreo con recordatorio anticipado', summary: 'Vuelo', eventDescription: 'Detalles del vuelo:\nAerolínea: \nVuelo #: \nPuerta: ' },
    ro: { name: 'Zbor', description: 'Călătorie cu avionul cu memento anticipat', summary: 'Zbor', eventDescription: 'Detalii zbor:\nCompanie aeriană: \nZbor #: \nPoartă: ' },
  },
  'builtin-deadline': {
    en: { name: 'Deadline', description: 'Project or task deadline', summary: 'Deadline' },
    es: { name: 'Fecha límite', description: 'Fecha límite de proyecto o tarea', summary: 'Fecha límite' },
    ro: { name: 'Termen limită', description: 'Termen limită de proiect sau sarcină', summary: 'Termen limită' },
  },
  'builtin-holiday': {
    en: { name: 'Holiday / Day Off', description: 'Vacation or public holiday', summary: 'Holiday' },
    es: { name: 'Vacaciones / Día libre', description: 'Vacaciones o día festivo', summary: 'Vacaciones' },
    ro: { name: 'Vacanță / Zi liberă', description: 'Vacanță sau sărbătoare legală', summary: 'Vacanță' },
  },
  'builtin-study': {
    en: { name: 'Study Session', description: 'Focused study or learning time', summary: 'Study Session', eventDescription: 'Topic: ' },
    es: { name: 'Sesión de estudio', description: 'Tiempo de estudio o aprendizaje', summary: 'Sesión de estudio', eventDescription: 'Tema: ' },
    ro: { name: 'Sesiune de studiu', description: 'Timp de studiu sau învățare', summary: 'Sesiune de studiu', eventDescription: 'Subiect: ' },
  },
  'builtin-weekly-recurring': {
    en: { name: 'Weekly Recurring', description: 'Generic weekly repeating event', summary: 'Weekly Event' },
    es: { name: 'Semanal recurrente', description: 'Evento semanal genérico', summary: 'Evento semanal' },
    ro: { name: 'Recurent săptămânal', description: 'Eveniment generic săptămânal', summary: 'Eveniment săptămânal' },
  },
}

export function getLocalizedTemplate(template: EventTemplate, language: Language): EventTemplate {
  const strings = TEMPLATE_I18N[template.id]?.[language]
  if (!strings) return template
  return {
    ...template,
    name: strings.name,
    description: strings.description,
    event: template.event ? {
      ...template.event,
      summary: strings.summary,
      ...(strings.eventDescription !== undefined ? { description: strings.eventDescription } : {}),
    } : template.event,
  }
}

export const DEFAULT_TEMPLATES: EventTemplate[] = [
  {
    id: 'builtin-meeting',
    name: 'Team Meeting',
    description: 'Standard team meeting with video call',
    icon: '👥',
    color: '#007aff',
    categories: ['Work', 'Meeting'],
    isBuiltIn: true,
    event: {
      summary: 'Team Meeting',
      description: 'Weekly team sync-up',
      allDay: false,
      categories: ['Work', 'Meeting'],
      color: '#007aff',
      transparency: 'OPAQUE',
      classification: 'PUBLIC',
      alarms: [{ uid: 'a1', action: 'DISPLAY', trigger: '-PT10M', triggerRelation: 'START', description: 'Meeting in 10 minutes', isDefault: true }],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-birthday',
    name: 'Birthday',
    description: 'All-day birthday celebration',
    icon: '🎂',
    color: '#ff2d55',
    categories: ['Personal', 'Birthday'],
    isBuiltIn: true,
    event: {
      summary: 'Birthday',
      description: 'Happy Birthday! 🎉',
      allDay: true,
      categories: ['Personal', 'Birthday'],
      color: '#ff2d55',
      transparency: 'TRANSPARENT',
      recurrenceRule: { frequency: 'YEARLY', interval: 1 },
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-doctor',
    name: 'Doctor Appointment',
    description: 'Medical appointment with reminder',
    icon: '🏥',
    color: '#34c759',
    categories: ['Health'],
    isBuiltIn: true,
    event: {
      summary: 'Doctor Appointment',
      description: '',
      allDay: false,
      categories: ['Health'],
      color: '#34c759',
      transparency: 'OPAQUE',
      classification: 'PRIVATE',
      alarms: [
        { uid: 'a1', action: 'DISPLAY', trigger: '-PT1H', triggerRelation: 'START', description: 'Appointment in 1 hour', isDefault: true },
        { uid: 'a2', action: 'DISPLAY', trigger: '-P1D', triggerRelation: 'START', description: 'Appointment tomorrow', isDefault: false },
      ],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-workout',
    name: 'Workout',
    description: 'Exercise session',
    icon: '💪',
    color: '#ff9500',
    categories: ['Health', 'Fitness'],
    isBuiltIn: true,
    event: {
      summary: 'Workout',
      description: '',
      allDay: false,
      categories: ['Health', 'Fitness'],
      color: '#ff9500',
      transparency: 'OPAQUE',
      alarms: [{ uid: 'a1', action: 'DISPLAY', trigger: '-PT15M', triggerRelation: 'START', description: 'Time to workout!', isDefault: true }],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-dinner',
    name: 'Dinner Reservation',
    description: 'Restaurant dinner with location',
    icon: '🍽️',
    color: '#af52de',
    categories: ['Social', 'Food'],
    isBuiltIn: true,
    event: {
      summary: 'Dinner Reservation',
      description: '',
      allDay: false,
      categories: ['Social', 'Food'],
      color: '#af52de',
      transparency: 'OPAQUE',
      alarms: [{ uid: 'a1', action: 'DISPLAY', trigger: '-PT30M', triggerRelation: 'START', description: 'Dinner in 30 minutes', isDefault: true }],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-flight',
    name: 'Flight',
    description: 'Air travel with early reminder',
    icon: '✈️',
    color: '#5856d6',
    categories: ['Travel'],
    isBuiltIn: true,
    event: {
      summary: 'Flight',
      description: 'Flight details:\nAirline: \nFlight #: \nGate: ',
      allDay: false,
      categories: ['Travel'],
      color: '#5856d6',
      transparency: 'OPAQUE',
      alarms: [
        { uid: 'a1', action: 'DISPLAY', trigger: '-PT3H', triggerRelation: 'START', description: 'Flight in 3 hours', isDefault: true },
        { uid: 'a2', action: 'DISPLAY', trigger: '-P1D', triggerRelation: 'START', description: 'Flight tomorrow', isDefault: false },
      ],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-deadline',
    name: 'Deadline',
    description: 'Project or task deadline',
    icon: '⏰',
    color: '#ff3b30',
    categories: ['Work', 'Deadline'],
    isBuiltIn: true,
    event: {
      summary: 'Deadline',
      description: '',
      allDay: true,
      categories: ['Work', 'Deadline'],
      color: '#ff3b30',
      transparency: 'TRANSPARENT',
      priority: 1,
      alarms: [
        { uid: 'a1', action: 'DISPLAY', trigger: '-P1D', triggerRelation: 'START', description: 'Deadline tomorrow', isDefault: true },
        { uid: 'a2', action: 'DISPLAY', trigger: '-P3D', triggerRelation: 'START', description: 'Deadline in 3 days', isDefault: false },
      ],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-holiday',
    name: 'Holiday / Day Off',
    description: 'Vacation or public holiday',
    icon: '🏖️',
    color: '#00c7be',
    categories: ['Holiday'],
    isBuiltIn: true,
    event: {
      summary: 'Holiday',
      description: '',
      allDay: true,
      categories: ['Holiday'],
      color: '#00c7be',
      transparency: 'TRANSPARENT',
      classification: 'PUBLIC',
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-study',
    name: 'Study Session',
    description: 'Focused study or learning time',
    icon: '📚',
    color: '#32ade6',
    categories: ['Education'],
    isBuiltIn: true,
    event: {
      summary: 'Study Session',
      description: 'Topic: ',
      allDay: false,
      categories: ['Education'],
      color: '#32ade6',
      transparency: 'OPAQUE',
      alarms: [{ uid: 'a1', action: 'DISPLAY', trigger: '-PT5M', triggerRelation: 'START', description: 'Study time!', isDefault: true }],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'builtin-weekly-recurring',
    name: 'Weekly Recurring',
    description: 'Generic weekly repeating event',
    icon: '🔄',
    color: '#8e8e93',
    categories: [],
    isBuiltIn: true,
    event: {
      summary: 'Weekly Event',
      description: '',
      allDay: false,
      categories: [],
      color: '#8e8e93',
      transparency: 'OPAQUE',
      recurrenceRule: { frequency: 'WEEKLY', interval: 1 },
      alarms: [{ uid: 'a1', action: 'DISPLAY', trigger: '-PT10M', triggerRelation: 'START', description: 'Event in 10 minutes', isDefault: true }],
    },
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
]
